name: Build
on:
  push:
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake . --preset=debug

      - name: Build
        working-directory: ${{github.workspace}}
        # Build your program with the given configuration
        run: cmake --build . --preset=debug

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest .